// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

package kv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PutAppendArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Op                   string   `protobuf:"bytes,3,opt,name=Op,proto3" json:"Op,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=Id,proto3" json:"Id,omitempty"`
	Seq                  int64    `protobuf:"varint,5,opt,name=Seq,proto3" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutAppendArgs) Reset()         { *m = PutAppendArgs{} }
func (m *PutAppendArgs) String() string { return proto.CompactTextString(m) }
func (*PutAppendArgs) ProtoMessage()    {}
func (*PutAppendArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

func (m *PutAppendArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAppendArgs.Unmarshal(m, b)
}
func (m *PutAppendArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAppendArgs.Marshal(b, m, deterministic)
}
func (m *PutAppendArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAppendArgs.Merge(m, src)
}
func (m *PutAppendArgs) XXX_Size() int {
	return xxx_messageInfo_PutAppendArgs.Size(m)
}
func (m *PutAppendArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAppendArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PutAppendArgs proto.InternalMessageInfo

func (m *PutAppendArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutAppendArgs) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PutAppendArgs) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *PutAppendArgs) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PutAppendArgs) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PutAppendReply struct {
	IsLeader             bool     `protobuf:"varint,1,opt,name=IsLeader,proto3" json:"IsLeader,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutAppendReply) Reset()         { *m = PutAppendReply{} }
func (m *PutAppendReply) String() string { return proto.CompactTextString(m) }
func (*PutAppendReply) ProtoMessage()    {}
func (*PutAppendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{1}
}

func (m *PutAppendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAppendReply.Unmarshal(m, b)
}
func (m *PutAppendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAppendReply.Marshal(b, m, deterministic)
}
func (m *PutAppendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAppendReply.Merge(m, src)
}
func (m *PutAppendReply) XXX_Size() int {
	return xxx_messageInfo_PutAppendReply.Size(m)
}
func (m *PutAppendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAppendReply.DiscardUnknown(m)
}

var xxx_messageInfo_PutAppendReply proto.InternalMessageInfo

func (m *PutAppendReply) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *PutAppendReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArgs) Reset()         { *m = GetArgs{} }
func (m *GetArgs) String() string { return proto.CompactTextString(m) }
func (*GetArgs) ProtoMessage()    {}
func (*GetArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{2}
}

func (m *GetArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArgs.Unmarshal(m, b)
}
func (m *GetArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArgs.Marshal(b, m, deterministic)
}
func (m *GetArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArgs.Merge(m, src)
}
func (m *GetArgs) XXX_Size() int {
	return xxx_messageInfo_GetArgs.Size(m)
}
func (m *GetArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetArgs proto.InternalMessageInfo

func (m *GetArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetReply struct {
	IsLeader             bool     `protobuf:"varint,1,opt,name=IsLeader,proto3" json:"IsLeader,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{3}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *GetReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PutAppendArgs)(nil), "PutAppendArgs")
	proto.RegisterType((*PutAppendReply)(nil), "PutAppendReply")
	proto.RegisterType((*GetArgs)(nil), "GetArgs")
	proto.RegisterType((*GetReply)(nil), "GetReply")
}

func init() {
	proto.RegisterFile("kv.proto", fileDescriptor_2216fe83c9c12408)
}

var fileDescriptor_2216fe83c9c12408 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0xc4, 0xb9, 0xf4, 0x81, 0x55, 0x1e, 0x1e, 0x42, 0xf5, 0x30, 0x72, 0xda, 0x29,
	0x07, 0xbd, 0x7a, 0xd9, 0xc5, 0x52, 0x26, 0x4c, 0x32, 0xd8, 0x7d, 0x2e, 0x0f, 0x11, 0x87, 0x8b,
	0x4d, 0x2a, 0xec, 0xbf, 0x97, 0x44, 0x5b, 0x28, 0x14, 0x76, 0x7b, 0xbf, 0xef, 0xf0, 0xbe, 0xdf,
	0x7b, 0x20, 0x3e, 0x7f, 0xb4, 0x6b, 0x8e, 0xe1, 0xa8, 0x3e, 0xe0, 0xea, 0xb5, 0x0d, 0x4b, 0xe7,
	0xe8, 0xcb, 0x2e, 0x9b, 0x77, 0x8f, 0x37, 0xc0, 0x57, 0x74, 0x92, 0xd9, 0x3c, 0x5b, 0xe4, 0x26,
	0x8e, 0x78, 0x0b, 0xd3, 0xed, 0xee, 0xd0, 0x92, 0x64, 0x29, 0xfb, 0x03, 0x2c, 0x80, 0xad, 0x9d,
	0xe4, 0x29, 0x62, 0x6b, 0x17, 0xb9, 0xb6, 0xf2, 0x62, 0x9e, 0x2d, 0xb8, 0x61, 0xb5, 0x8d, 0x7b,
	0x36, 0xf4, 0x2d, 0xa7, 0x29, 0x88, 0xa3, 0x7a, 0x86, 0xa2, 0xaf, 0x32, 0xe4, 0x0e, 0x27, 0x2c,
	0x41, 0xd4, 0xfe, 0x85, 0x76, 0x96, 0x9a, 0x54, 0x28, 0x4c, 0xcf, 0x28, 0x61, 0xb6, 0x69, 0xf7,
	0x7b, 0xf2, 0x3e, 0xf5, 0x0a, 0xd3, 0xa1, 0xba, 0x83, 0x59, 0x45, 0x61, 0x5c, 0x56, 0x3d, 0x81,
	0xa8, 0x28, 0x9c, 0x5f, 0x3f, 0x7a, 0xd4, 0x83, 0x01, 0xb6, 0xda, 0xa2, 0x86, 0xbc, 0x17, 0xc5,
	0x42, 0x0f, 0xfe, 0x53, 0x5e, 0xeb, 0xe1, 0x11, 0x6a, 0x82, 0xf7, 0xc0, 0x2b, 0x0a, 0x28, 0xf4,
	0xbf, 0x56, 0x99, 0xeb, 0xce, 0x41, 0x4d, 0xde, 0x2e, 0xd3, 0xa3, 0x1f, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x66, 0x0e, 0xb3, 0x34, 0x74, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KVClient is the client API for KV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVClient interface {
	// Sends a greeting
	PutAppend(ctx context.Context, in *PutAppendArgs, opts ...grpc.CallOption) (*PutAppendReply, error)
	Get(ctx context.Context, in *GetArgs, opts ...grpc.CallOption) (*GetReply, error)
}

type kVClient struct {
	cc grpc.ClientConnInterface
}

func NewKVClient(cc grpc.ClientConnInterface) KVClient {
	return &kVClient{cc}
}

func (c *kVClient) PutAppend(ctx context.Context, in *PutAppendArgs, opts ...grpc.CallOption) (*PutAppendReply, error) {
	out := new(PutAppendReply)
	err := c.cc.Invoke(ctx, "/KV/PutAppend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Get(ctx context.Context, in *GetArgs, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/KV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServer is the server API for KV service.
type KVServer interface {
	// Sends a greeting
	PutAppend(context.Context, *PutAppendArgs) (*PutAppendReply, error)
	Get(context.Context, *GetArgs) (*GetReply, error)
}

// UnimplementedKVServer can be embedded to have forward compatible implementations.
type UnimplementedKVServer struct {
}

func (*UnimplementedKVServer) PutAppend(ctx context.Context, req *PutAppendArgs) (*PutAppendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAppend not implemented")
}
func (*UnimplementedKVServer) Get(ctx context.Context, req *GetArgs) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterKVServer(s *grpc.Server, srv KVServer) {
	s.RegisterService(&_KV_serviceDesc, srv)
}

func _KV_PutAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAppendArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).PutAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KV/PutAppend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).PutAppend(ctx, req.(*PutAppendArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Get(ctx, req.(*GetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _KV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "KV",
	HandlerType: (*KVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutAppend",
			Handler:    _KV_PutAppend_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KV_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}
