// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package raft

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type RequestVoteArgs struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	CandidateId          int32    `protobuf:"varint,2,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	LastLogIndex         int32    `protobuf:"varint,3,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          int32    `protobuf:"varint,4,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteArgs) Reset()         { *m = RequestVoteArgs{} }
func (m *RequestVoteArgs) String() string { return proto.CompactTextString(m) }
func (*RequestVoteArgs) ProtoMessage()    {}
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *RequestVoteArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteArgs.Unmarshal(m, b)
}
func (m *RequestVoteArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteArgs.Marshal(b, m, deterministic)
}
func (m *RequestVoteArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteArgs.Merge(m, src)
}
func (m *RequestVoteArgs) XXX_Size() int {
	return xxx_messageInfo_RequestVoteArgs.Size(m)
}
func (m *RequestVoteArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteArgs proto.InternalMessageInfo

func (m *RequestVoteArgs) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteArgs) GetCandidateId() int32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteArgs) GetLastLogIndex() int32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteArgs) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

// The response message containing the greetings
type RequestVoteReply struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteReply) Reset()         { *m = RequestVoteReply{} }
func (m *RequestVoteReply) String() string { return proto.CompactTextString(m) }
func (*RequestVoteReply) ProtoMessage()    {}
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *RequestVoteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteReply.Unmarshal(m, b)
}
func (m *RequestVoteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteReply.Marshal(b, m, deterministic)
}
func (m *RequestVoteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteReply.Merge(m, src)
}
func (m *RequestVoteReply) XXX_Size() int {
	return xxx_messageInfo_RequestVoteReply.Size(m)
}
func (m *RequestVoteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteReply proto.InternalMessageInfo

func (m *RequestVoteReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReply) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type AppendEntries struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntries) Reset()         { *m = AppendEntries{} }
func (m *AppendEntries) String() string { return proto.CompactTextString(m) }
func (*AppendEntries) ProtoMessage()    {}
func (*AppendEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *AppendEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntries.Unmarshal(m, b)
}
func (m *AppendEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntries.Marshal(b, m, deterministic)
}
func (m *AppendEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntries.Merge(m, src)
}
func (m *AppendEntries) XXX_Size() int {
	return xxx_messageInfo_AppendEntries.Size(m)
}
func (m *AppendEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntries.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntries proto.InternalMessageInfo

type AppendEntriesArgs struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId             int32    `protobuf:"varint,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	PrevLogIndex         int32    `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          int32    `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	Log                  []byte   `protobuf:"bytes,5,opt,name=Log,proto3" json:"Log,omitempty"`
	LeaderCommit         int32    `protobuf:"varint,6,opt,name=LeaderCommit,proto3" json:"LeaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesArgs) Reset()         { *m = AppendEntriesArgs{} }
func (m *AppendEntriesArgs) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesArgs) ProtoMessage()    {}
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *AppendEntriesArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesArgs.Unmarshal(m, b)
}
func (m *AppendEntriesArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesArgs.Marshal(b, m, deterministic)
}
func (m *AppendEntriesArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesArgs.Merge(m, src)
}
func (m *AppendEntriesArgs) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesArgs.Size(m)
}
func (m *AppendEntriesArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesArgs proto.InternalMessageInfo

func (m *AppendEntriesArgs) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesArgs) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesArgs) GetPrevLogIndex() int32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesArgs) GetPrevLogTerm() int32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesArgs) GetLog() []byte {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *AppendEntriesArgs) GetLeaderCommit() int32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesReply struct {
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	ConflictIndex        int32    `protobuf:"varint,3,opt,name=ConflictIndex,proto3" json:"ConflictIndex,omitempty"`
	ConflictTerm         int32    `protobuf:"varint,4,opt,name=ConflictTerm,proto3" json:"ConflictTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesReply) Reset()         { *m = AppendEntriesReply{} }
func (m *AppendEntriesReply) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesReply) ProtoMessage()    {}
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{4}
}

func (m *AppendEntriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesReply.Unmarshal(m, b)
}
func (m *AppendEntriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesReply.Marshal(b, m, deterministic)
}
func (m *AppendEntriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesReply.Merge(m, src)
}
func (m *AppendEntriesReply) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesReply.Size(m)
}
func (m *AppendEntriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesReply proto.InternalMessageInfo

func (m *AppendEntriesReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesReply) GetConflictIndex() int32 {
	if m != nil {
		return m.ConflictIndex
	}
	return 0
}

func (m *AppendEntriesReply) GetConflictTerm() int32 {
	if m != nil {
		return m.ConflictTerm
	}
	return 0
}

type L2SAppendEntriesReply struct {
	//string message = 1;
	Term                 int32    `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	ConflictIndex        int32    `protobuf:"varint,3,opt,name=ConflictIndex,proto3" json:"ConflictIndex,omitempty"`
	ConflictTerm         int32    `protobuf:"varint,4,opt,name=ConflictTerm,proto3" json:"ConflictTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2SAppendEntriesReply) Reset()         { *m = L2SAppendEntriesReply{} }
func (m *L2SAppendEntriesReply) String() string { return proto.CompactTextString(m) }
func (*L2SAppendEntriesReply) ProtoMessage()    {}
func (*L2SAppendEntriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{5}
}

func (m *L2SAppendEntriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2SAppendEntriesReply.Unmarshal(m, b)
}
func (m *L2SAppendEntriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2SAppendEntriesReply.Marshal(b, m, deterministic)
}
func (m *L2SAppendEntriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2SAppendEntriesReply.Merge(m, src)
}
func (m *L2SAppendEntriesReply) XXX_Size() int {
	return xxx_messageInfo_L2SAppendEntriesReply.Size(m)
}
func (m *L2SAppendEntriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_L2SAppendEntriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_L2SAppendEntriesReply proto.InternalMessageInfo

func (m *L2SAppendEntriesReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *L2SAppendEntriesReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *L2SAppendEntriesReply) GetConflictIndex() int32 {
	if m != nil {
		return m.ConflictIndex
	}
	return 0
}

func (m *L2SAppendEntriesReply) GetConflictTerm() int32 {
	if m != nil {
		return m.ConflictTerm
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestVoteArgs)(nil), "RequestVoteArgs")
	proto.RegisterType((*RequestVoteReply)(nil), "RequestVoteReply")
	proto.RegisterType((*AppendEntries)(nil), "AppendEntries")
	proto.RegisterType((*AppendEntriesArgs)(nil), "AppendEntriesArgs")
	proto.RegisterType((*AppendEntriesReply)(nil), "AppendEntriesReply")
	proto.RegisterType((*L2SAppendEntriesReply)(nil), "L2SAppendEntriesReply")
}

func init() {
	proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b)
}

var fileDescriptor_b042552c306ae59b = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xcd, 0x6a, 0xc2, 0x40,
	0x10, 0xc7, 0xdd, 0xfa, 0x51, 0x19, 0x15, 0x75, 0x4a, 0x21, 0x78, 0x92, 0xa5, 0x07, 0x4f, 0x39,
	0xd8, 0x9e, 0x7a, 0x13, 0xe9, 0x87, 0x90, 0x43, 0x89, 0xd2, 0x7b, 0x6a, 0x46, 0x09, 0x68, 0x36,
	0xdd, 0xac, 0xc5, 0xbe, 0x43, 0x4b, 0x1f, 0xa9, 0xaf, 0x56, 0x76, 0x8d, 0xb2, 0x89, 0xe4, 0xde,
	0xdb, 0xce, 0x2f, 0xcb, 0xce, 0xff, 0x37, 0x4c, 0x00, 0x64, 0xb0, 0x52, 0x6e, 0x22, 0x85, 0x12,
	0xfc, 0x9b, 0x41, 0xd7, 0xa7, 0xf7, 0x1d, 0xa5, 0xea, 0x55, 0x28, 0x9a, 0xc8, 0x75, 0x8a, 0x08,
	0xb5, 0x05, 0xc9, 0xad, 0xc3, 0x86, 0x6c, 0x54, 0xf7, 0xcd, 0x19, 0x87, 0xd0, 0x9a, 0x06, 0x71,
	0x18, 0x85, 0x81, 0xa2, 0x59, 0xe8, 0x5c, 0x98, 0x4f, 0x36, 0x42, 0x0e, 0x6d, 0x2f, 0x48, 0x95,
	0x27, 0xd6, 0xb3, 0x38, 0xa4, 0xbd, 0x53, 0x35, 0x57, 0x72, 0x4c, 0xbf, 0x92, 0xd5, 0xa6, 0x41,
	0xed, 0xf0, 0x8a, 0x85, 0xf8, 0x33, 0xf4, 0xac, 0x38, 0x3e, 0x25, 0x9b, 0xcf, 0xb2, 0x3c, 0xfa,
	0xc2, 0x93, 0x0c, 0x62, 0x45, 0x87, 0x3c, 0x4d, 0xdf, 0x46, 0xbc, 0x0b, 0x9d, 0x49, 0x92, 0x50,
	0x1c, 0x3e, 0xc4, 0x4a, 0x46, 0x94, 0xf2, 0x5f, 0x06, 0xfd, 0x1c, 0x29, 0x95, 0x1d, 0x40, 0xd3,
	0xa3, 0x20, 0x24, 0x79, 0x32, 0x3d, 0xd5, 0x5a, 0xf3, 0x45, 0xd2, 0x47, 0x51, 0xd3, 0x66, 0x3a,
	0x5c, 0x56, 0xdb, 0x9a, 0x16, 0xc2, 0x1e, 0x54, 0x3d, 0xb1, 0x76, 0xea, 0x43, 0x36, 0x6a, 0xfb,
	0xfa, 0x68, 0xc6, 0x67, 0x7a, 0x4c, 0xc5, 0x76, 0x1b, 0x29, 0xa7, 0x91, 0x8d, 0xcf, 0x62, 0xfc,
	0x8b, 0x01, 0xe6, 0x0c, 0xca, 0xe7, 0xe3, 0xc0, 0xe5, 0x7c, 0xb7, 0x5c, 0x52, 0x9a, 0x66, 0xb3,
	0x39, 0x96, 0x78, 0x03, 0x9d, 0xa9, 0x88, 0x57, 0x9b, 0x68, 0xa9, 0x6c, 0x83, 0x3c, 0xd4, 0x71,
	0x8e, 0xc0, 0x72, 0xc8, 0x31, 0xfe, 0xc3, 0xe0, 0xda, 0x1b, 0xcf, 0xff, 0x4f, 0xa2, 0xf1, 0x1e,
	0x6a, 0xfe, 0xe4, 0x71, 0x81, 0x77, 0xd0, 0xb2, 0xb6, 0x08, 0x7b, 0x6e, 0x61, 0xc5, 0x07, 0x7d,
	0xb7, 0xb8, 0x65, 0xbc, 0x82, 0xf7, 0x85, 0x8d, 0x41, 0x74, 0xcf, 0xf6, 0x65, 0x70, 0xe5, 0x9e,
	0xfb, 0xf2, 0xca, 0x5b, 0xc3, 0xfc, 0x4e, 0xb7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0x5a,
	0x0a, 0xae, 0x5c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RAFTClient is the client API for RAFT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RAFTClient interface {
	// Sends a greeting
	RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteReply, error)
	AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesReply, error)
}

type rAFTClient struct {
	cc grpc.ClientConnInterface
}

func NewRAFTClient(cc grpc.ClientConnInterface) RAFTClient {
	return &rAFTClient{cc}
}

func (c *rAFTClient) RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteReply, error) {
	out := new(RequestVoteReply)
	err := c.cc.Invoke(ctx, "/RAFT/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAFTClient) AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesReply, error) {
	out := new(AppendEntriesReply)
	err := c.cc.Invoke(ctx, "/RAFT/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAFTServer is the server API for RAFT service.
type RAFTServer interface {
	// Sends a greeting
	RequestVote(context.Context, *RequestVoteArgs) (*RequestVoteReply, error)
	AppendEntries(context.Context, *AppendEntriesArgs) (*AppendEntriesReply, error)
}

// UnimplementedRAFTServer can be embedded to have forward compatible implementations.
type UnimplementedRAFTServer struct {
}

func (*UnimplementedRAFTServer) RequestVote(ctx context.Context, req *RequestVoteArgs) (*RequestVoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (*UnimplementedRAFTServer) AppendEntries(ctx context.Context, req *AppendEntriesArgs) (*AppendEntriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}

func RegisterRAFTServer(s *grpc.Server, srv RAFTServer) {
	s.RegisterService(&_RAFT_serviceDesc, srv)
}

func _RAFT_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAFTServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RAFT/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAFTServer).RequestVote(ctx, req.(*RequestVoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAFT_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAFTServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RAFT/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAFTServer).AppendEntries(ctx, req.(*AppendEntriesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _RAFT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RAFT",
	HandlerType: (*RAFTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RAFT_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _RAFT_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
